#---------------------
# Use /cmd_vel topic provided by move_base
use_move_base: false

# Will use desired velocities otherwise
velocity_x: 0.0
velocity_y: 0.0
velocity_yaw: 0.0
foot_height: 0.08 
body_height: 0.27 
#---------------------

#Search radius for foothold adaptation. Not used in blind mode
foothold_search_radius: 0.1


#---------------------
#MPC settings
mpc_step_dt: 0.02
mpc_horizon_steps: 15
#---------------------


#---------------------
# Frequency settings for body trajectory planner's lowpass filters
# Stairs
height_lpf_freq: 30.0
pitch_lpf_freq: 10.0

# Sparse stepping stones
#height_lpf_freq: 0.9
#pitch_lpf_freq: 0.9
#---------------------

# Update footholds during the whole swing phase
upd_footholds_continuously: false

gait: trot

# Use local planner with or without elevation_mapping
blind: true

# Use cheater odometry from simulation
perfect_odometry: true
