velocityX: 0.5
velocityY: 0.0
velocityYaw: 0.0
footHeight: 0.08 
bodyHeight: 0.26 

foothold_search_radius: 0.1

mpc_step_dt: 0.02
mpc_horizon_steps: 15

# Stairs
height_lpf_freq: 30.0
pitch_lpf_freq: 10.0

# Sparse stepping stones
#height_lpf_freq: 0.9
#pitch_lpf_freq: 0.9

# Update footholds during the whole swing phase
upd_footholds_continuously: true

gait: trot