global_frame: map

robot_base_frame: trunk

footprint: [[0.1, 0.1], [0.1, -0.1], [-0.1, -0.1], [-0.1, 0.1]]

inflation_radius: 1.75
cost_scaling_factor: 2.58

map_type: costmap
clearing_rotation_allowed: false