obstacle_range: 6.0
raytrace_range: 8.5
footprint: [[0.3, 0.2], [0.3, -0.2], [-0.4, -0.2], [-0.4, 0.2]]
map_topic: /map
subscribe_to_updates: true
always_send_full_costmap: true

global_frame: odom
robot_base_frame: trunk

static_layer:
    map_topic: /map
    subscribe_to_updates: true

plugins:
    - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
#   - {name: obstacle_layer,         type: "costmap_2d::ObstacleLayer"}

#obstacle_layer:
#  observation_sources: laser_scan_sensor
#  laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 5.0, obstacle_range: 6.0, raytrace_range: 8.5}
