global_costmap:
  global_frame: odom
  robot_base_frame: trunk

  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 0.5

  static_map: true

  width: 30
  height: 30
  origin_x: -15
  origin_y: -15
  rolling_window: true
  
  resolution: 0.02