local_costmap:
  global_frame: odom
  robot_base_frame: trunk

  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 0.3 

  static_map: true  
  rolling_window: true
  width: 10
  height: 10
  resolution: 0.02

  obstacle_range: 5.0
  raytrace_range: 5.5