base_local_planner: "dwa_local_planner/DWAPlannerROS"

DWAPlannerROS:
  holonomic_robot: true

  # Tolerances                  Defaults
  yaw_goal_tolerance: 0.05      # 0.05
  xy_goal_tolerance:  0.3      # 0.10
  latch_xy_goal_tolerance: true # false

  # Forward simulation          Defaults
  use_dwa: true                 # true
  sim_time: 4.0                 # 1.7
  sim_granularity: 0.025        # 0.025
  angular_sim_granularity: 0.1 # 0.10 (1 degree = 0.017 rad)
  vx_samples: 20                 # 3
  vy_samples: 20                # 10
  vth_samples: 40               # 20

  # Acceleration and velocity limits
  acc_lim_x: 2.0                # 2.5
  acc_lim_y: 2.0                # 2.5
  acc_lim_th: 5.0            # 3.2

  max_vel_x: +0.5
  min_vel_x: -0.4
  max_vel_y: +0.2
  min_vel_y: -0.2

  max_vel_theta: 2.5
  min_vel_theta: 0.1

  # Other                       Defaults
  oscillation_reset_dist: 0.05  # 0.05
  oscillation_reset_angle: 0.20 # 0.20
  prune_plan: false             # true
  trans_stopped_vel: 0.1        # 0.1
  theta_stopped_vel: 0.1          # 0.1
  publish_cost_grid_pc: false    # false


  path_distance_bias: 1.0
  goal_distance_bias: 0.8
  occdist_scale: 0.01