input_sources:
  ground_truth_cloud: # A name to identify the input source
    type: pointcloud # Supported types: pointcloud
    topic: /livox/lidar
    queue_size: 1
    publish_on_update: true # Whether to publish the elevation map after a callback from this source.
    sensor_processor:
      type: perfect

map_frame_id: "odom"
robot_base_frame_id: "trunk"
robot_pose_with_covariance_topic: "" # Leaving this empty skipps pose covariance updates.
robot_pose_cache_size: 100
#fused_map_publishing_rate: 1
#min_update_rate: 1
#relocate_rate: 0.2
track_point_frame_id: "trunk"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
enable_visibility_cleanup: false
postprocessor_num_threads: 4